joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
gazebo_ros_control/pid_gains:
  joint_1: {p: 0.0, i: 0.0, d: 0.0}
  joint_2: {p: 0.0, i: 0.0, d: 0.0}
  joint_3: {p: 0.0, i: 0.0, d: 0.0}
  joint_4: {p: 0.0, i: 0.0, d: 0.0}
  joint_5: {p: 0.0, i: 0.0, d: 0.0}
  joint_6: {p: 0.0, i: 0.0, d: 0.0}
  gripper_finger1_joint: {p: 0.0, i: 0.0, d: 0.0}